environment:
  home: C:\projects
  cmake: C:\projects\cmake-3.4.1-win32-x86\bin\cmake.exe

version: '{branch}-{build}'

os: Visual Studio 2015

install:
  # Get a recent CMake and our dependencies (Eigen, OpenCV, Boost):
  - cmd: cd %home%
  - ps: wget https://cmake.org/files/v3.4/cmake-3.4.1-win32-x86.zip -OutFile cmake.zip
  - cmd: 7z x cmake.zip -o"C:\projects" -y > nul # will extract to cmake-3.4.1-win32-x86\
  - cmd: '%cmake% --version'

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: '%cmake% -G "Visual Studio 14 Win64" -DUSE_SSE=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=OFF -DBOOST_ROOT=C:\Libraries\boost_1_59_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_59_0\lib64-msvc-14.0 -DCMAKE_INSTALL_PREFIX=..\install ..\tiny-cnn'

build:
  project: C:\projects\build\tiny_cnn.sln
